version: 3

includes:
  server:
    taskfile: ./ce/server/Taskfile.yml
    dir: ./ce/server/

# env file:
dotenv:
  - .env

tasks:
  run:
    cmds:
      - go run main.go

  web:install:
    cmds:
      - cd web/; yarn install;

  run:web:
    cmds:
      - cd web/; yarn start;

  docs:
    cmds:
      - open http://localhost:9000/swagger

  push:
    cmds:
      - task: server:push